sqlcomponents/sqlcomponents

.github/workflows/ci-publish.yml
compiler/src/test/java/org/sqlcomponents/compiler/java/JavaCompilerTest.java

Formatter Issue 2

---

.github/workflows/ci-publish.yml
compiler/src/main/resources/template/java/method/InsertStatement.ftl
compiler/src/main/resources/template/java/method/UpdateStatement.ftl
compiler/src/test/java/org/sqlcomponents/compiler/java/JavaCompilerTest.java
core/src/main/java/org/sqlcomponents/core/model/Entity.java
datastore/src/test/java/org/example/store/MovieStoreTest.java

Partial Update and Auditing Fixes

---

compiler/src/main/resources/template/java/Manager.ftl
compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl
compiler/src/main/resources/template/java/method/SelectStatement.ftl
compiler/src/main/resources/template/java/method/UpdateStatement.ftl
datastore/src/test/java/org/example/store/RajaTest.java

Select by SQL

---

compiler/src/main/resources/template/java/columns.ftl
compiler/src/main/resources/template/java/custom-object/json.ftl
compiler/src/main/resources/template/java/custom-object/jsonb.ftl
compiler/src/main/resources/template/java/custom-object/uuid.ftl
compiler/src/main/resources/template/java/method/UpdateStatement.ftl
datastore/src/test/java/org/example/store/RajaTest.java

Custom Column Changes

---

compiler/src/main/resources/template/java/method/DeleteStatement.ftl
compiler/src/main/resources/template/java/method/UpdateStatement.ftl
datastore/src/test/java/org/example/store/RajaTest.java

Update and Delete with Query

---

datastore/src/test/resources/data/postgres/Raja.json
init.db/postgres/raja.sql

[Mapper] Support for bpchar in POSTGRES 

---

checkstyle-suppressions.xml
core/src/main/java/org/sqlcomponents/core/model/Default.java
core/src/main/java/org/sqlcomponents/core/model/Entity.java
core/src/main/java/org/sqlcomponents/core/model/ORM.java
core/src/main/java/org/sqlcomponents/core/model/relational/Column.java
core/src/main/java/org/sqlcomponents/core/model/relational/Database.java
core/src/main/java/org/sqlcomponents/core/model/relational/Index.java
core/src/main/java/org/sqlcomponents/core/model/relational/Procedure.java
pom.xml

Delombok to Move to Immutable #104

---

compiler/src/main/java/org/sqlcomponents/compiler/java/mapper/JavaMapper.java
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGGeometryTypeTest.java
core/src/main/java/org/sqlcomponents/core/model/relational/enums/ColumnType.java
init.db/postgres/raja.sql
pom.xml

Added the *Geometry data type* which is line segment.

[Mapper]Support for Geometric Data types (Line Segment Type) #90

---

compiler/src/main/java/org/sqlcomponents/compiler/java/mapper/JavaMapper.java
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGNetworkTypeTest.java
core/src/main/java/org/sqlcomponents/core/model/relational/enums/ColumnType.java
init.db/postgres/raja.sql

Network datatype "inet" is added

[Mapper] Support for Network Address Data Types(Inet Type) #95

---

compiler/src/main/java/org/sqlcomponents/compiler/java/mapper/JavaMapper.java
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGPointTypeTest.java
core/src/main/java/org/sqlcomponents/core/model/relational/enums/ColumnType.java
init.db/postgres/raja.sql

Support for Geometric Data types (Point Type)

---

compiler/pom.xml
compiler/src/main/java/org/sqlcomponents/compiler/java/mapper/JavaMapper.java
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGGeometryLineTypeTest.java
core/src/main/java/org/sqlcomponents/core/model/relational/enums/ColumnType.java
init.db/postgres/raja.sql

I have successfully converted the Line Datatype in PostgreSQL to suitable datatype in Java.

[Mapper]Support for Geometric Data types (Line Type) #89

---

compiler/src/main/resources/template/java/custom-object/json.ftl
compiler/src/main/resources/template/java/custom-object/jsonb.ftl

done changes in json.ftl and jsonb.ftl

[Compiler] H2 JSON not parsed properly #134

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

made changes in column.ftl and store.ftl

[Compiler] Support for Network Address Data Types(Inet Type) #113

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

i have made changes in column.ftl and store.ftl files.

[Compiler]Support for Geometric Data types (Circles Type) #112

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

I have made changes in columns.ftl and Store.ftl files.

[Compiler]Support for Geometric Data types (Path Type) #110

---

docker-compose.yml
init.db/h2db/azagu_raja.sql
init.db/h2db/movie.sql

added h2 database configuration code

my level-2 code commit

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

Changed store.ftl and column.ftl for macaddress network datatype

[Compiler] Support for Network Address Data Types(MACADDR Type) #115

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

made changes in columns.ftl and Store.ftl files

[Compiler] Support for Network Address Data Types(MACADDR8 Type) #116

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

made changes in store.ftl and colum.ftl

[Compiler]Support for Geometric Data types (Polygon Type) #111

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl

Made changes with columns and Store.ftl

[Compiler]Support for Geometric Data types (Line Type) #107

---

compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGPointTypeTest.java
init.db/postgres/raja.sql

created compiler support for point data type

[Compiler]Support for Geometric Data types (Point Type) #150

---

compiler/src/main/resources/template/java/Manager.ftl
compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl
compiler/src/main/resources/template/java/custom-object/box.ftl
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGBoxTypeTest.java
init.db/postgres/raja.sql

Compiler support for Geometric type Box datatype is added.

[Compiler]Support for Geometric Data types (Box Type) #109

---

compiler/src/main/java/org/sqlcomponents/compiler/java/mapper/JavaMapper.java
compiler/src/main/resources/template/java/Manager.ftl
compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGNetworkMacaddr8TypeTest.java
init.db/postgres/raja.sql

I have add network address data type macaddr8

Support for Network Address Data Types(MACADDR8 Type) #116

---

compiler/src/main/resources/template/java/Manager.ftl
compiler/src/main/resources/template/java/Store.ftl
compiler/src/main/resources/template/java/columns.ftl
compiler/src/main/resources/template/java/custom-object/line.ftl
compiler/src/test/java/org/sqlcomponents/compiler/java/mapper/postgresql/PGGeometryLineTypeTest.java
init.db/postgres/raja.sql

Created compiler support for line geometric datatype

Added compiler support for line geometric datatype

---

datastore/checkstyle-suppressions.xml

https://github.com/sqlcomponents/sqlcomponents/issues/174

https://github.com/sqlcomponents/sqlcomponents/issues/174

---

README.md
compiler/src/main/java/org/sqlcomponents/compiler/template/FTLTemplate.java
compiler/src/main/java/org/sqlcomponents/compiler/template/directive/ColumnSelectionDirective.java
compiler/src/main/resources/template/java/Model.ftl
compiler/src/main/resources/template/java/jdbcbase.ftl
compiler/src/main/resources/template/java/method/SelectStatement.ftl

Can we make this in java ? [#176](https://github.com/sqlcomponents/sqlcomponents/issues/176)

[Misc] Can we make this in java ? #176

---

compiler/src/main/resources/template/java/method/InsertStatement.ftl
compiler/src/main/resources/template/java/method/SelectStatement.ftl
compiler/src/main/resources/template/java/method/UpdateStatement.ftl

I removed the  space character at the start of the select, insert, and update queries.

fixed sql spacing issue

---

compiler/src/main/resources/template/java/method/SelectStatement.ftl

I Changed the count(*) to Count(id).

Using Primary key column in count query instead of *
